---
version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
    - "9094:9094"
    environment:
    - "KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://${HOST_IP:-localhost}:9094"
    - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - "KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094"
    - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
    - "KAFKA_CREATE_TOPICS=streaming-transformed:1:1,streaming-dead-letters:1:1,streaming-validated:1:1,streaming-raw:1:1"
    - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
    healthcheck:
      test: ["CMD-SHELL", "cat /opt/kafka/logs/server.log | grep \"Previous Leader Epoch was: -1\""]
      interval: 10s
      timeout: 20s
      retries: 3
  metastore:
    image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/metastore-testo:latest
    depends_on:
    - postgres
    ports:
    - "9083:9083"
    command: >
      /bin/bash -c "
        /opt/hive-metastore/bin/schematool -dbType postgres -validate || /opt/hive-metastore/bin/schematool -dbType postgres -initSchema;
        /opt/hive-metastore/bin/start-metastore"
  postgres:
    logging:
      driver: none
    image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/postgres-testo:latest
    ports:
    - "5432:5432"
  minio:
    image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/minio-testo:latest
    ports:
    - "9000:9000"
  presto:
    depends_on:
    - metastore
    - minio
    image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/presto-testo:latest
    ports:
    - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/v1/info | grep -q '\"starting\":false'"]
      interval: 10s
      timeout: 30s
      retries: 10
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D 'cn=admin,dc=example,dc=org' -w admin"]
      interval: 5s
      timeout: 20s
      retries: 3
